### PR TITLE
Fix incompatibility with Angular 8.x and up.

### PR DESCRIPTION
**Pull request by josteink**
This closes https://github.com/OfficeDev/office-ui-fabric-core/issues/1192.

### CODE REVIEW

**Comment by josteink** [comment]
Not sure what the proper way to fix this is. Could someone please provide me some leads?

**Comment by viceice** [comment]
i think you need to move the required mixin to the docs sass file

**Comment by josteink** [comment]
Build-errors fixed. Would be nice if someone could look into this issue now.

Not being able to work with a modern Angular-version is quite a show-stopper.

**Comment by lindalu-MSFT** [comment]
@josteink Thanks for your help! I don't monitor this repo regularly unless I get a security alert so please @lindalu-MSFT me if you need me to merge anything. Cheers!

**Pull request merged**
