### PR TITLE
Update NPM, Bower, and NuGet packages for Fabric Core 3.0

### PR DESCRIPTION
**Pull request by mikewheaton**
This PR updates the configuration for NPM, Bower, and NuGet to reflect the change in name "Office UI Fabric" to "Office UI Fabric Core" and the version bump to 3.0.0.

### CODE REVIEW

**Comment by Jahnp** [comment]
Approved 💃 

Should the 3.0 release be amended to include these? If you've already published to NPM, we may need to publish a 3.0.1 patch to account for this change.

**Comment by mikewheaton** [comment]
These changes were already made on the `release/3.0.0` branch, so the packages were all published just fine. We used to cherry pick those commits directly back onto `master` but now that we have `master` protected, all changes have to be made via a pull request like this one. No need for a patch release. 😄

**Comment by Jahnp** [comment]
Gotcha--perfect! Just making sure :)

**Comment by ericthompson** [comment]
Approved

**Pull request merged**
