### PR TITLE
Added !default to variables

### PR DESCRIPTION
**Pull request by lafe**
As discussed in issue #805, Office UI Fabric currently does not support customization, which is necessary if customers have their own branding. 
This pull requests adds the [`!default`](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_) flag to the variables defined in the Office UI Fabric. This flag tells SASS to leave the value of a variable unchanged, if it is already defined. With this approach, you can define your own values in a separate file and include them in the build process of your custom Office UI Fabric. Only those values will be set to their default values, that have not been defined previously in your own variables file.

Your custom SASS file might look like the following:
``` SASS
@import "fabricVariables"; //Includes your variables
@import "fabric"; //Main Fabric.scss file (located elsewhere, included in the sass build process)
@import "fabric.components"; //Main SCSS for components (located elsewhere, included in the sass build process)

//Your additional customizations
```

### CODE REVIEW

**Comment by mikewheaton** [comment]
Approved. This is a great idea, as developers can override variables without actually modifying Fabric itself.

**Comment by Jahnp** [comment]
Approved. Super super cool--thanks for the contribution @lafe! It does look like there are conflicts with `master` now, though--once those have been resolved we'd be happy to merge this in.

**Comment by lafe** [comment]
After merging the current master branch in my local repository, I was unable to spot any conflicts. Please let me know, if there are specific problems you encounter.

**Comment by Jahnp** [comment]
Strange, that didn't seem to resolve the conflicts that GH was reporting. I've updated the PR and verified that your changes are all still there, so once CI finishes I'll go ahead and merge this in. Thanks again for the contribution @lafe!

**Pull request merged**
