### PR TITLE
Update remaining link to new CDN

### PR DESCRIPTION
**Pull request by mikewheaton**
Found one remaining reference to the old CDN in the documentation. This PR updates it to the new CDN.

### CODE REVIEW

**Comment by Jahnp** [comment]
Approved

**Comment by ericthompson** [comment]
Approved!

**Comment by mikewheaton** [comment]
Not sure what PullApprove has against Peter. It doesn't seem to be recognizing his approval here.

**Comment by Jahnp** [comment]
Approved

Maybe this time?

**Comment by Jahnp** [comment]
Weird... that totally worked.

**Pull request merged**
