### PR TITLE
Update messaging for M365 Developer Program

### PR DESCRIPTION
**Pull request by ElizabethSamuel-MSFT**

### CODE REVIEW

**Comment by ElizabethSamuel-MSFT** [comment]
@Lauragra Do review. Thanks.

**Review by Lauragra — APPROVED** [review]

**Comment by ElizabethSamuel-MSFT** [comment]
@Lauragra Thanks for reviewing.

Repo owners: Please review and merge.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@micahgodbolt Can you help review and merge this PR? Or connect us to current owner? Thanks.

**Comment by micahgodbolt** [comment]
Can you explain why these changes are being made?

**Comment by ElizabethSamuel-MSFT** [comment]
> Can you explain why these changes are being made?

@Lauragra Can you respond to this? Thanks.

**Comment by micahgodbolt** [comment]
Here's the blogpost describing the changes to the program.

https://devblogs.microsoft.com/microsoft365dev/stay-ahead-of-the-game-with-the-latest-updates-to-the-microsoft-365-developer-program/

**Review by micahgodbolt — APPROVED** [review]

**Pull request merged**
